variables:
  CICD_SCRIPTS_DIR: "automation/cicd"
  # test line        

stages:
  - Generate+Validate Terraform
  - Apply in AWS
  - Provision
  - Permissions

################### BASE TEMPLATES ######################
.docker_terraform:
  image:
    name: deiverk/ubuntu_terraform_python3:latest
    entrypoint: [""]
  only:
    refs:
      - /^((feature/.*))$/
      - /^((develop/.*))$/


# Apply the Terraform files in AWS root account
Plan and Apply in AWS:
  extends: .docker_terraform
  stage: Apply in AWS
  tags:
    - docker
  script:
    - ${CICD_SCRIPTS_DIR}/plan_apply_in_aws.sh
  cache:
    paths:
      - terraform/*.tf
  only:
    changes:
      - terraform/**/*
      - automation/cicd/.gitlab-ci.yml
      - automation/cicd/plan_apply_in_aws.sh

# Jobs
# Generates and Validates the Terraform files
Validate Terraform files:
  extends: .docker_terraform
  stage: Generate+Validate Terraform
  tags:
    - docker
  script:
    - ${CICD_SCRIPTS_DIR}/generate_validate_tf_files.sh
  cache:
    paths:
      - terraform/*.tf
  only:
    changes:
      - terraform/**/*
      - automation/cicd/.gitlab-ci.yml
      - automation/cicd/generate_validate_tf_files.sh
      - automation/cicd/terraform-pre-run.py

# Template job
configure_aws_config:
  stage: Provision
  tags:
    - shell
  script:
    - pwd
    - ls
  only:
    refs:
      - develop
    changes:
      - gitlab-ci.yml